name = "MacroTools"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.1"

[deps]
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"

[compat]
julia = "â‰¥ 1.0"
